module.exports = [
  {
    type: 'bar',
    dataFile: 'netzeingriffe_jahre_2015_2025.csv',
    outputFile: 'massnahmenenergie.js',
    containerId: 'netzeingriffe-jahre-massnahmenenergie',
    title: '',
    xAxisLabel: 'Jahr',
    yAxisLabel: 'GWh',
    xKey: 'jahr',
    yKey: 'massnahmenenergie_gwh',
    color: '#d5a62c',
  },
  {
    type: 'line',
    dataFile: 'netzeingriffe_jahre_2015_2025.csv',
    outputFile: 'kosten.js',
    containerId: 'netzeingriffe-jahre-kosten',
    title: '',
    xAxisLabel: 'Jahr',
    yAxisLabel: 'Mio. €',
    xKey: 'jahr',
    yKey: 'kosten_mio_eur',
    smooth: true,
    colors: ['#cb6573'],
  },
  {
    type: 'line',
    dataFile: 'netzeingriffe_monate_2022_2026.csv',
    outputFile: 'monate.js',
    containerId: 'netzeingriffe-monate',
    title: '',
    xAxisLabel: 'Monat',
    yAxisLabel: 'GWh',
    xKey: 'monat',
    seriesKeys: ['gesamt_gwh', 'redispatch_marktkraftwerke_gwh'],
    seriesNames: ['Netzengpassmanagement insgesamt', 'davon Redispatch mit Marktkraftwerken'],
    colors: ['#5470c6', '#469c8a'],
    smooth: true,
  },
];
