models:
  - name: bnetza_windkraft_ausschreibung
    description: "cleaning bnetza_windkraft_ausschreibung"
    columns:
      - name: verfahren
        description: "Ausschreibungsverfahren"
        data-tests:
          - not_null
      - name: gebotstermin
        description: "Gebotsterminsdatum"
        data-tests:
          - not_null
          - unique
      - name: zuschlagsmenge_kw
        description: "Zuschlagsmenge in kW"
        data-tests:
          - not_null
      - name: gebotsmenge_kw
        description: "Gebotsmenge in kW"
        data-tests:
          - not_null
      - name: ausschreibungsvolumen_kw
        description: "Ausschreibungsvolumen in kW"
        data-tests:
          - not_null
      - name: zuschlagswert_ct_kwh_gew_mittel
        description: "Zuschlagswert in ct/kWh (Gewichteter Mittelwert)"
        data-tests:
          - not_null
