queries:
- name: ren_share_daily_avg
  description: "Daily average renewable energy share in Germany"
  api_params:
    year: [2025, 2024, 2023, 2022, 2021, 2020, 2019, 2018, 2017, 2016, 2015]
    country: ['de']
